# Generated by Django 3.1.1 on 2021-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_db',
            name='tasktimedate',
            field=models.CharField(max_length=50),
        ),
    ]
